# Generated by Django 5.2.15 on 2026-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='artists/photos/'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_upload',
            field=models.FileField(blank=True, null=True, upload_to='songs/audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_upload',
            field=models.ImageField(blank=True, null=True, upload_to='songs/covers/'),
        ),
    ]
