-- TesoHub Music permanent persistence schema for Supabase PostgreSQL.
-- This migration is intentionally additive and safe to run before cutover.
-- It does not delete or mutate the legacy JSON database or Render uploads.

create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'music-audio',
    'music-audio',
    false,
    83886080,
    array[
      'audio/aac',
      'audio/flac',
      'audio/m4a',
      'audio/mp4',
      'audio/mpeg',
      'audio/ogg',
      'audio/opus',
      'audio/wav',
      'audio/webm',
      'audio/x-m4a',
      'audio/x-wav'
    ]
  ),
  (
    'artwork',
    'artwork',
    true,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
  ),
  (
    'avatars',
    'avatars',
    true,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.listeners (
  id bigint generated by default as identity primary key,
  name text not null default '',
  email text not null default '',
  phone text not null default '',
  password_hash text not null default '',
  role text not null default 'listener'
    check (role in ('listener', 'artist_pending', 'artist')),
  plan text not null default 'free',
  status text not null default 'active'
    check (status in ('active', 'suspended')),
  artist_id bigint,
  artist_application_id bigint,
  suspension_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create unique index if not exists listeners_email_unique
  on public.listeners (lower(email))
  where nullif(email, '') is not null;

create unique index if not exists listeners_phone_unique
  on public.listeners (phone)
  where nullif(phone, '') is not null;

create table if not exists public.artists (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default '',
  bio text not null default '',
  photo_path text,
  legacy_photo text not null default '',
  location text not null default '',
  is_featured boolean not null default false,
  status text not null default 'active'
    check (status in ('active', 'suspended', 'removed')),
  owner_listener_id bigint references public.listeners(id) on delete set null,
  source_application_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists artists_status_idx on public.artists (status);
create index if not exists artists_featured_idx on public.artists (is_featured);

create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.artist_applications (
  id bigint generated by default as identity primary key,
  listener_id bigint references public.listeners(id) on delete cascade,
  artist_id bigint references public.artists(id) on delete set null,
  artist_name text not null default '',
  contact_name text not null default '',
  bio text not null default '',
  country text not null default '',
  region text not null default '',
  genre text not null default '',
  genre_note text not null default '',
  phone text not null default '',
  email text not null default '',
  photo_path text,
  legacy_photo text not null default '',
  social_link text not null default '',
  genuine_confirmed boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'changes_requested')),
  review_reason text not null default '',
  rejection_reason text not null default '',
  reviewed_by text not null default '',
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists artist_applications_listener_idx
  on public.artist_applications (listener_id);
create index if not exists artist_applications_status_idx
  on public.artist_applications (status);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  title text not null,
  audio_path text,
  legacy_audio_file text not null default '',
  cover_path text,
  legacy_cover_image text not null default '',
  genre text not null default '',
  genre_note text not null default '',
  lyrics text not null default '',
  play_count bigint not null default 0 check (play_count >= 0),
  release_date date,
  is_featured boolean not null default false,
  status text not null default 'published'
    check (status in ('published', 'hidden', 'removed', 'under_review')),
  source_release_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists songs_artist_idx on public.songs (artist_id);
create index if not exists songs_status_idx on public.songs (status);
create index if not exists songs_featured_play_idx
  on public.songs (is_featured desc, play_count desc);

create table if not exists public.releases (
  id bigint generated by default as identity primary key,
  artist_id bigint references public.artists(id) on delete cascade,
  listener_id bigint references public.listeners(id) on delete set null,
  title text not null default '',
  release_type text not null default 'Single',
  featured_artist text not null default '',
  genre text not null default '',
  genre_note text not null default '',
  language text not null default '',
  release_date date,
  explicit boolean not null default false,
  producer text not null default '',
  songwriter text not null default '',
  description text not null default '',
  rights_confirmed boolean not null default false,
  audio_path text,
  legacy_audio_file text not null default '',
  cover_path text,
  legacy_cover_image text not null default '',
  status text not null default 'draft'
    check (status in ('draft', 'under_review', 'approved', 'rejected', 'scheduled', 'published')),
  rejection_reason text not null default '',
  review_reason text not null default '',
  public_song_id bigint references public.songs(id) on delete set null,
  submitted_at timestamptz,
  approved_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists releases_artist_idx on public.releases (artist_id);
create index if not exists releases_listener_idx on public.releases (listener_id);
create index if not exists releases_status_idx on public.releases (status);

create table if not exists public.auth_tokens (
  id text primary key,
  listener_id bigint not null references public.listeners(id) on delete cascade,
  token_hash text not null unique,
  device_id text not null default '',
  device_name text not null default '',
  created_at timestamptz not null default now(),
  last_active_at timestamptz
);

create index if not exists auth_tokens_listener_idx on public.auth_tokens (listener_id);

create table if not exists public.song_likes (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs(id) on delete cascade,
  listener_id bigint references public.listeners(id) on delete cascade,
  device_id text not null default '',
  created_at timestamptz not null default now()
);

create unique index if not exists song_likes_song_listener_unique
  on public.song_likes (song_id, listener_id)
  where listener_id is not null;

create unique index if not exists song_likes_song_device_unique
  on public.song_likes (song_id, device_id)
  where nullif(device_id, '') is not null;

create table if not exists public.artist_follows (
  id bigint generated by default as identity primary key,
  artist_id bigint not null references public.artists(id) on delete cascade,
  listener_id bigint references public.listeners(id) on delete cascade,
  device_id text not null default '',
  created_at timestamptz not null default now()
);

create unique index if not exists artist_follows_artist_listener_unique
  on public.artist_follows (artist_id, listener_id)
  where listener_id is not null;

create unique index if not exists artist_follows_artist_device_unique
  on public.artist_follows (artist_id, device_id)
  where nullif(device_id, '') is not null;

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.listeners(id) on delete cascade,
  name text not null,
  description text not null default '',
  artwork_path text,
  legacy_artwork text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists playlists_owner_idx on public.playlists (owner_id);

create table if not exists public.playlist_songs (
  id bigint generated by default as identity primary key,
  playlist_id bigint not null references public.playlists(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  position integer not null default 0,
  added_at timestamptz not null default now()
);

create unique index if not exists playlist_songs_unique
  on public.playlist_songs (playlist_id, song_id);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint references public.listeners(id) on delete set null,
  target_type text not null default 'content',
  target_id bigint,
  reason text not null default '',
  status text not null default 'open'
    check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_target_idx on public.reports (target_type, target_id);

create table if not exists public.listening_history (
  id bigint generated by default as identity primary key,
  song_id bigint references public.songs(id) on delete cascade,
  listener_id bigint references public.listeners(id) on delete set null,
  device_id text not null default '',
  source text not null default 'api',
  played_at timestamptz not null default now()
);

create index if not exists listening_history_song_idx on public.listening_history (song_id);
create index if not exists listening_history_listener_idx on public.listening_history (listener_id);

create table if not exists public.platform_settings (
  id integer primary key default 1 check (id = 1),
  registration_enabled boolean not null default true,
  artist_applications_enabled boolean not null default true,
  music_uploads_enabled boolean not null default true,
  maintenance_mode boolean not null default false,
  maintenance_message text not null default 'TesoHub Music is temporarily under maintenance.',
  max_audio_upload_mb integer not null default 80,
  max_artwork_upload_mb integer not null default 10,
  supported_audio_formats text[] not null default array['mp3', 'm4a', 'aac', 'wav', 'flac', 'ogg', 'opus', 'webm'],
  minimum_supported_app_version text not null default '',
  app_announcement text not null default '',
  updated_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.feature_flags (
  key text primary key,
  enabled boolean not null default true,
  updated_at timestamptz
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user text not null default '',
  admin_role text not null default 'super_admin',
  action text not null,
  target_type text not null default 'system',
  target_id bigint,
  details jsonb not null default '{}'::jsonb,
  reason text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_idx
  on public.admin_audit_logs (created_at desc);

create table if not exists public.legacy_media_migrations (
  legacy_value text primary key,
  bucket text not null,
  object_path text not null,
  source_kind text not null,
  bytes bigint not null default 0,
  content_type text not null default '',
  migrated_at timestamptz not null default now()
);

create table if not exists public.migration_runs (
  id uuid primary key default gen_random_uuid(),
  source_name text not null,
  source_fingerprint text not null,
  summary jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create or replace view public.users as
select * from public.listeners;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'listeners_artist_id_fkey'
  ) then
    alter table public.listeners
      add constraint listeners_artist_id_fkey
      foreign key (artist_id) references public.artists(id) on delete set null
      deferrable initially deferred;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'listeners_artist_application_id_fkey'
  ) then
    alter table public.listeners
      add constraint listeners_artist_application_id_fkey
      foreign key (artist_application_id) references public.artist_applications(id) on delete set null
      deferrable initially deferred;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'artists_source_application_id_fkey'
  ) then
    alter table public.artists
      add constraint artists_source_application_id_fkey
      foreign key (source_application_id) references public.artist_applications(id) on delete set null
      deferrable initially deferred;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'songs_source_release_id_fkey'
  ) then
    alter table public.songs
      add constraint songs_source_release_id_fkey
      foreign key (source_release_id) references public.releases(id) on delete set null
      deferrable initially deferred;
  end if;
end $$;
