-- Support V1 for TesoHub Music.
-- Additive only: creates support tables and a private attachment bucket.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'support-attachments',
  'support-attachments',
  false,
  8388608,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'application/pdf',
    'text/plain'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists tesohub_music.support_tickets (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  listener_id bigint not null references tesohub_music.listeners(id) on delete cascade,
  account_email text not null default '',
  account_username text not null default '',
  requester_role text not null default 'listener'
    check (requester_role in ('listener', 'artist')),
  category text not null,
  subject text not null,
  message text not null,
  status text not null default 'open'
    check (status in ('open', 'in_progress', 'waiting_on_user', 'resolved', 'closed')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  assigned_to text not null default '',
  attachment_bucket text not null default '',
  attachment_path text not null default '',
  attachment_name text not null default '',
  attachment_type text not null default '',
  attachment_size bigint not null default 0 check (attachment_size >= 0),
  last_user_reply_at timestamptz,
  last_admin_reply_at timestamptz,
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_listener_updated_idx
  on tesohub_music.support_tickets (listener_id, updated_at desc);

create index if not exists support_tickets_status_updated_idx
  on tesohub_music.support_tickets (status, updated_at desc);

create index if not exists support_tickets_category_idx
  on tesohub_music.support_tickets (category);

create index if not exists support_tickets_assigned_to_idx
  on tesohub_music.support_tickets (assigned_to)
  where nullif(assigned_to, '') is not null;

create index if not exists support_tickets_search_idx
  on tesohub_music.support_tickets
  using gin (
    to_tsvector(
      'simple',
      coalesce(reference, '') || ' ' ||
      coalesce(account_email, '') || ' ' ||
      coalesce(account_username, '') || ' ' ||
      coalesce(category, '') || ' ' ||
      coalesce(subject, '') || ' ' ||
      coalesce(message, '')
    )
  );

create table if not exists tesohub_music.support_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references tesohub_music.support_tickets(id) on delete cascade,
  author_type text not null check (author_type in ('user', 'admin')),
  listener_id bigint references tesohub_music.listeners(id) on delete set null,
  admin_username text not null default '',
  message text not null,
  attachment_bucket text not null default '',
  attachment_path text not null default '',
  attachment_name text not null default '',
  attachment_type text not null default '',
  attachment_size bigint not null default 0 check (attachment_size >= 0),
  created_at timestamptz not null default now()
);

create index if not exists support_messages_ticket_created_idx
  on tesohub_music.support_messages (ticket_id, created_at, id);

create table if not exists tesohub_music.support_internal_notes (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references tesohub_music.support_tickets(id) on delete cascade,
  admin_username text not null default '',
  note text not null,
  created_at timestamptz not null default now()
);

create index if not exists support_internal_notes_ticket_created_idx
  on tesohub_music.support_internal_notes (ticket_id, created_at, id);

create table if not exists tesohub_music.support_assignments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references tesohub_music.support_tickets(id) on delete cascade,
  assigned_to text not null default '',
  assigned_by text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists support_assignments_ticket_created_idx
  on tesohub_music.support_assignments (ticket_id, created_at desc, id desc);
