-- Repair Support V1 identity defaults if the tables were created without them.
-- Additive only: preserves existing support rows and sets each sequence after max(id).

do $$
declare
  target_table text;
  full_table text;
  sequence_name text;
  max_id bigint;
begin
  foreach target_table in array array[
    'support_tickets',
    'support_messages',
    'support_internal_notes',
    'support_assignments'
  ]
  loop
    full_table := format('tesohub_music.%I', target_table);

    if exists (
      select 1
      from information_schema.columns
      where table_schema = 'tesohub_music'
        and table_name = target_table
        and column_name = 'id'
        and identity_generation is null
        and column_default is null
    ) then
      execute format(
        'alter table %s alter column id add generated by default as identity',
        full_table
      );
    end if;

    sequence_name := pg_get_serial_sequence(full_table, 'id');
    if sequence_name is not null then
      execute format('select coalesce(max(id), 0) from %s', full_table) into max_id;
      perform setval(sequence_name, max_id + 1, false);
    end if;
  end loop;
end $$;
